#!/usr/bin/env python3
"""Populate all 6 CSV data files for the make-decision skill."""
import csv
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


def write_csv(filename, headers, rows):
    filepath = os.path.join(DATA_DIR, filename)
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(rows)
    print(f"  Written {len(rows)} rows to {filename}")


def populate_frameworks():
    headers = ["Framework", "Category", "Keywords", "Description", "When to Use", "Steps", "Strengths", "Limitations", "Best For", "Complexity"]
    rows = [
        {
            "Framework": "Hypothesis-Driven Decision Tree",
            "Category": "hypothesis-driven",
            "Keywords": "hypothesis, day one answer, evidence, testing, iterative, structured, strategic",
            "Description": "Form a Day One answer (initial hypothesis), decompose into testable sub-hypotheses, gather evidence to confirm or refute, then refine. Avoids boiling-the-ocean analysis by focusing on what matters.",
            "When to Use": "Complex strategic decisions with incomplete information where exhaustive analysis is impractical",
            "Steps": "1. State your Day One answer (best current hypothesis). 2. Decompose into 3-5 testable sub-hypotheses. 3. For each sub-hypothesis, identify what evidence would prove/disprove it. 4. Gather minimum viable evidence. 5. Update hypothesis based on findings. 6. Repeat until confidence is sufficient.",
            "Strengths": "Prevents analysis paralysis; focuses effort on highest-value questions; naturally iterative",
            "Limitations": "Requires discipline to update hypothesis honestly; initial framing bias possible",
            "Best For": "Strategic Direction, Decision Under Uncertainty",
            "Complexity": "High",
        },
        {
            "Framework": "Logic Tree Option Decomposition",
            "Category": "decomposition",
            "Keywords": "logic tree, MECE, options, exhaustive, decompose, map, alternatives, mutually exclusive, collectively exhaustive",
            "Description": "Use MECE logic trees to map ALL options and sub-options exhaustively. Ensures no alternatives are missed before evaluation begins.",
            "When to Use": "Multi-option decisions where the full option space is unclear or risk of missing alternatives is high",
            "Steps": "1. State the decision question clearly. 2. List top-level options (MECE). 3. For each option, decompose into sub-options. 4. Test completeness: are all possibilities covered? 5. Test exclusivity: do options overlap? 6. Prune obviously unviable branches. 7. Evaluate remaining options.",
            "Strengths": "Guarantees completeness; visual and structured; prevents premature narrowing",
            "Limitations": "Can be time-consuming for simple decisions; may generate too many options without clear prioritization",
            "Best For": "Multi-Option Selection, Resource Allocation",
            "Complexity": "Medium",
        },
        {
            "Framework": "Weighted Criteria Matrix",
            "Category": "evaluation",
            "Keywords": "weighted, criteria, matrix, scoring, comparison, evaluation, weights, transparent, auditable, score",
            "Description": "Define evaluation criteria, assign weights based on priorities, score each option 1-5 on each criterion, calculate weighted totals. Explicit, transparent, and auditable.",
            "When to Use": "Multi-option decisions with clear evaluation criteria where transparency and traceability matter",
            "Steps": "1. List all options to evaluate. 2. Define 5-8 evaluation criteria. 3. Assign weights (must sum to 100). 4. Score each option 1-5 on each criterion. 5. Calculate weighted scores. 6. Compare totals and review sensitivity.",
            "Strengths": "Transparent and auditable; reduces emotional bias; easy to communicate; supports group alignment",
            "Limitations": "Requires agreement on criteria and weights upfront; can create false precision; garbage-in-garbage-out",
            "Best For": "Multi-Option Selection, Group / Stakeholder Decision",
            "Complexity": "Medium",
        },
        {
            "Framework": "Sensitivity Analysis Decision",
            "Category": "stress-test",
            "Keywords": "sensitivity, assumptions, variables, uncertainty, flip, robustness, tornado, what-if",
            "Description": "Test which assumptions or criteria changes would flip the decision. Identifies what matters most and what is noise. Reveals decision robustness.",
            "When to Use": "Decisions where confidence in key inputs is uncertain and you need to know which assumptions actually matter",
            "Steps": "1. Identify the current leading option. 2. List all key assumptions and inputs. 3. For each assumption, vary it across plausible range. 4. Record which variations change the decision. 5. Rank assumptions by decision impact. 6. Focus additional analysis only on decision-sensitive assumptions.",
            "Strengths": "Reveals what actually drives the decision; prevents over-analysis of non-sensitive factors; builds confidence",
            "Limitations": "Requires a quantifiable decision model; may miss interaction effects between variables",
            "Best For": "Decision Under Uncertainty, Resource Allocation",
            "Complexity": "High",
        },
        {
            "Framework": "Expected Value Calculation",
            "Category": "evaluation",
            "Keywords": "expected value, probability, outcomes, rational, uncertainty, calculation, quantitative, EV",
            "Description": "Assign probabilities to outcomes, multiply by value, sum for each option. The rational choice under uncertainty when outcomes and probabilities can be estimated.",
            "When to Use": "Decisions with quantifiable outcomes and estimable probabilities where rational optimization is appropriate",
            "Steps": "1. List all possible outcomes for each option. 2. Estimate probability of each outcome. 3. Estimate value (monetary or utility) of each outcome. 4. Multiply probability x value for each. 5. Sum expected values per option. 6. Choose highest EV (adjusted for risk tolerance).",
            "Strengths": "Mathematically rigorous; handles uncertainty explicitly; comparable across options",
            "Limitations": "Requires probability and value estimates that may be unreliable; ignores risk preference; poor for one-shot decisions",
            "Best For": "Resource Allocation, Decision Under Uncertainty",
            "Complexity": "Medium",
        },
        {
            "Framework": "Scenario Planning Matrix",
            "Category": "stress-test",
            "Keywords": "scenario, planning, uncertainty, futures, robustness, external, environment, strategic, ambiguity",
            "Description": "Define 2-3 key external uncertainties, build 4-9 scenarios from combinations, evaluate each option across all scenarios. Identifies robust choices that perform well regardless of future.",
            "When to Use": "Strategic decisions with high external uncertainty where the future environment is genuinely unknowable",
            "Steps": "1. Identify 2-3 key external uncertainties (not in your control). 2. Define 2-3 plausible values for each. 3. Build scenario matrix (combinations). 4. Name each scenario and describe it. 5. Evaluate each option under each scenario. 6. Select option that is robust across scenarios or identify hedging strategies.",
            "Strengths": "Handles deep uncertainty; prevents overcommitment to single forecast; builds organizational preparedness",
            "Limitations": "Can generate too many scenarios; subjective scenario selection; does not assign probabilities",
            "Best For": "Strategic Direction, Decision Under Uncertainty",
            "Complexity": "High",
        },
        {
            "Framework": "Pros-Cons-Fixes Analysis",
            "Category": "evaluation",
            "Keywords": "pros, cons, fixes, advantages, disadvantages, mitigate, quick, simple, binary, tradeoff",
            "Description": "List pros and cons for each option, then for each con ask 'can it be fixed or mitigated?' Transforms binary thinking into nuanced evaluation by exploring whether downsides are addressable.",
            "When to Use": "Binary or few-option decisions needing quick assessment where a simple structured approach is sufficient",
            "Steps": "1. List all pros for each option. 2. List all cons for each option. 3. For each con, ask: can this be fixed, mitigated, or is it permanent? 4. Mark fixable cons differently from permanent ones. 5. Re-evaluate: does the option look different once fixable cons are addressed? 6. Decide based on remaining permanent trade-offs.",
            "Strengths": "Simple and fast; accessible to all stakeholders; reveals that many cons are solvable; reduces fear-based rejection",
            "Limitations": "Not rigorous for complex multi-option decisions; no weighting mechanism; subjective assessment of fixability",
            "Best For": "Binary Choice, Operational / Tactical",
            "Complexity": "Low",
        },
        {
            "Framework": "Pre-Mortem Decision Test",
            "Category": "stress-test",
            "Keywords": "pre-mortem, failure, risk, blind spots, stress test, retrospective, prospective hindsight, assume failure",
            "Description": "Assume the decision has already failed catastrophically. Work backward to identify what went wrong. Surfaces blind spots and risks before committing.",
            "When to Use": "High-stakes irreversible decisions where undetected risks could be catastrophic",
            "Steps": "1. State the proposed decision clearly. 2. Imagine it is 12 months later and the decision failed spectacularly. 3. Each participant independently writes what went wrong. 4. Share and compile all failure modes. 5. Categorize by likelihood and severity. 6. For high-risk failure modes, develop mitigation plans or reconsider the decision.",
            "Strengths": "Surfaces hidden risks; overcomes optimism bias; psychologically safe way to critique; works well in groups",
            "Limitations": "Can be demoralizing if overused; may generate unlikely risks; requires honest participation",
            "Best For": "Strategic Direction, Group / Stakeholder Decision",
            "Complexity": "Low",
        },
        {
            "Framework": "Reversibility Filter",
            "Category": "meta-framework",
            "Keywords": "reversibility, one-way door, two-way door, speed, iterate, meta, decision speed, reversible, irreversible",
            "Description": "Classify the decision as a one-way door (irreversible, high stakes) or two-way door (reversible, can iterate). Two-way doors should be decided quickly; one-way doors deserve deep analysis.",
            "When to Use": "Any decision — as the first step to determine how much analysis effort is warranted",
            "Steps": "1. Ask: If this decision turns out wrong, can we reverse or significantly change it? 2. If YES (two-way door): decide quickly, set a review date, iterate. 3. If NO (one-way door): invest in thorough analysis, use other frameworks. 4. If PARTIALLY reversible: identify which aspects are reversible and which are not. 5. Apply proportional analytical effort.",
            "Strengths": "Prevents over-analysis of reversible decisions; ensures proper investment in irreversible ones; meta-framework that improves decision speed",
            "Limitations": "Oversimplifies — most decisions are partially reversible; binary classification may be too coarse",
            "Best For": "Operational / Tactical, Time-Pressured Decision",
            "Complexity": "Low",
        },
        {
            "Framework": "Iterative Hypothesis Testing",
            "Category": "hypothesis-driven",
            "Keywords": "iterative, hypothesis, testing, bayesian, evidence, update, learn, experiment, minimum viable, data-poor",
            "Description": "Start with your best guess, design a minimum viable test, update based on evidence, repeat. Bayesian approach that learns from small experiments before full commitment.",
            "When to Use": "Data-poor environments where learning is possible before full commitment, and iteration is feasible",
            "Steps": "1. State initial hypothesis (best guess with current information). 2. Identify the cheapest way to test it (minimum viable experiment). 3. Define what evidence would confirm or refute. 4. Run the test. 5. Update hypothesis based on results (Bayesian update). 6. Repeat until confidence is sufficient or deadline requires decision.",
            "Strengths": "Minimizes cost of learning; naturally self-correcting; works with incomplete data; reduces commitment risk",
            "Limitations": "Requires ability to test before committing; slower for time-pressured decisions; may never reach full confidence",
            "Best For": "Decision Under Uncertainty, Operational / Tactical",
            "Complexity": "Medium",
        },
    ]
    write_csv("decision-frameworks.csv", headers, rows)


def populate_types():
    headers = ["Decision Type", "Keywords", "Characteristics", "Recommended Frameworks", "Analysis Methods", "Common Pitfalls", "Warning Signs", "Example Scenarios"]
    rows = [
        {
            "Decision Type": "Binary Choice",
            "Keywords": "binary, yes no, either or, two options, go no-go, accept reject, A or B",
            "Characteristics": "Two clear options. Often seems simple but may hide complexity. The key risk is that the choice is framed too narrowly.",
            "Recommended Frameworks": "Pros-Cons-Fixes, Pre-Mortem Decision Test",
            "Analysis Methods": "Break-Even Analysis, Pre-Mortem Analysis",
            "Common Pitfalls": "False binary — forcing two options when more exist. Not questioning whether the framing itself is correct.",
            "Warning Signs": "Someone says 'we either do X or we don't'. Only two options on the table. No exploration of alternatives.",
            "Example Scenarios": "Accept or reject a job offer. Go or no-go on a product launch. Acquire or pass on a target company.",
        },
        {
            "Decision Type": "Multi-Option Selection",
            "Keywords": "multiple options, comparison, evaluate, choose between, selection, several alternatives, ranking",
            "Characteristics": "Three or more options to evaluate. Needs structured comparison framework. Risk of choice overload without filtering.",
            "Recommended Frameworks": "Weighted Criteria Matrix, Logic Tree Option Decomposition",
            "Analysis Methods": "Relative Value Scoring, Sensitivity Analysis",
            "Common Pitfalls": "Choice overload — too many options without filtering. Comparing on inconsistent criteria. Anchoring to the first option evaluated.",
            "Warning Signs": "More than 5 options without clear criteria. Team members advocating different options without shared evaluation framework.",
            "Example Scenarios": "Selecting a CRM platform from 6 vendors. Choosing between 4 office locations. Picking a technology stack from multiple alternatives.",
        },
        {
            "Decision Type": "Resource Allocation",
            "Keywords": "resource, allocation, budget, distribute, prioritize, funding, investment, capacity, headcount, limited",
            "Characteristics": "Distributing limited resources (budget, time, people) across competing priorities. Not either/or but how much for each.",
            "Recommended Frameworks": "Expected Value Calculation, Sensitivity Analysis Decision",
            "Analysis Methods": "Expected Value Calculation, Opportunity Cost Assessment, Break-Even Analysis",
            "Common Pitfalls": "Peanut butter spreading — dividing equally instead of prioritizing. Sunk cost trap — allocating based on past investment not future value.",
            "Warning Signs": "Budget splits look identical to last year. Every team gets the same percentage. No explicit prioritization framework used.",
            "Example Scenarios": "Allocating R&D budget across 5 product lines. Distributing marketing spend across channels. Assigning engineering capacity to features.",
        },
        {
            "Decision Type": "Strategic Direction",
            "Keywords": "strategic, long-term, direction, vision, mission, pivot, transformation, irreversible, high-impact, future",
            "Characteristics": "Long-term, high-impact, often irreversible. Shapes future option space. Requires deep analysis and stakeholder alignment.",
            "Recommended Frameworks": "Scenario Planning Matrix, Hypothesis-Driven Decision Tree",
            "Analysis Methods": "Scenario Analysis, Decision Tree Analysis, Reference Class Forecasting",
            "Common Pitfalls": "Analysis paralysis — over-analyzing when decisive action is needed. Consensus-seeking that produces lowest-common-denominator strategy.",
            "Warning Signs": "Decision has been discussed for months without resolution. Multiple strategy consultants involved. The decision will be very difficult to reverse.",
            "Example Scenarios": "Entering a new geographic market. Pivoting business model from B2C to B2B. Major technology platform migration. M&A decisions.",
        },
        {
            "Decision Type": "Operational / Tactical",
            "Keywords": "operational, tactical, short-term, execution, process, workflow, reversible, optimization, incremental",
            "Characteristics": "Short-term, lower-impact, typically reversible. Optimize within existing strategy. Speed of decision often matters more than perfection.",
            "Recommended Frameworks": "Reversibility Filter, Iterative Hypothesis Testing",
            "Analysis Methods": "Break-Even Analysis, Relative Value Scoring",
            "Common Pitfalls": "Over-engineering — applying heavy frameworks to lightweight decisions. Escalating decisions that should be made locally.",
            "Warning Signs": "Decision affects only the next 1-3 months. Easy to change course if wrong. Low cost of being wrong.",
            "Example Scenarios": "Choosing a meeting schedule. Selecting a project management tool. Deciding sprint priorities. Setting a pricing experiment.",
        },
        {
            "Decision Type": "Decision Under Uncertainty",
            "Keywords": "uncertainty, unknown, ambiguous, incomplete data, risk, probability, unknown unknowns, volatile",
            "Characteristics": "Key variables are unknown or unknowable. Must decide despite incomplete data. The quality of the decision process matters more than the outcome.",
            "Recommended Frameworks": "Scenario Planning Matrix, Expected Value Calculation, Iterative Hypothesis Testing",
            "Analysis Methods": "Scenario Analysis, Bayesian Update Protocol, Reference Class Forecasting",
            "Common Pitfalls": "False precision — pretending you have more certainty than you do. Waiting for perfect information that will never arrive.",
            "Warning Signs": "Key assumptions are unverifiable. Experts disagree significantly. Historical data is limited or non-existent.",
            "Example Scenarios": "Launching a product in an unproven market. Investing in emerging technology. Navigating regulatory uncertainty. Planning for post-crisis recovery.",
        },
        {
            "Decision Type": "Group / Stakeholder Decision",
            "Keywords": "group, stakeholder, team, consensus, alignment, politics, committee, board, collaborative, multi-party",
            "Characteristics": "Multiple people with different interests, information, and authority must align. Communication and facilitation matter as much as analysis.",
            "Recommended Frameworks": "Pre-Mortem Decision Test, Weighted Criteria Matrix",
            "Analysis Methods": "Pre-Mortem Analysis, Relative Value Scoring",
            "Common Pitfalls": "Groupthink — premature consensus without challenging assumptions. HIPPO effect — highest-paid person's opinion dominates.",
            "Warning Signs": "Multiple stakeholders with competing priorities. Decision requires buy-in from people with different incentives. Political dynamics are significant.",
            "Example Scenarios": "Board deciding on strategic direction. Cross-functional team selecting a vendor. Partnership negotiations. Organizational restructuring decisions.",
        },
        {
            "Decision Type": "Time-Pressured Decision",
            "Keywords": "urgent, deadline, time pressure, fast, speed, window, time-sensitive, rapid, crisis",
            "Characteristics": "Deadline forces decision before ideal analysis is complete. Must optimize the trade-off between decision speed and decision quality.",
            "Recommended Frameworks": "Reversibility Filter, Pros-Cons-Fixes Analysis",
            "Analysis Methods": "Pre-Mortem Analysis, Opportunity Cost Assessment",
            "Common Pitfalls": "Premature closure — deciding too fast without sufficient consideration. OR delay — missing the window by seeking more information.",
            "Warning Signs": "External deadline is immutable. Competitor action forces response. Opportunity window is closing. Crisis requires immediate action.",
            "Example Scenarios": "Responding to a competitor announcement. Crisis management decisions. Time-limited acquisition opportunity. Emergency resource reallocation.",
        },
    ]
    write_csv("decision-types.csv", headers, rows)


def populate_biases():
    headers = ["Bias", "Category", "Keywords", "Description", "Impact on Decisions", "How to Detect", "Debiasing Strategy", "Example", "Severity"]
    rows = [
        {
            "Bias": "Confirmation Bias",
            "Category": "information-processing",
            "Keywords": "confirmation, selective evidence, cherry-picking, disconfirming, preferred option, validation seeking",
            "Description": "The tendency to seek, interpret, and remember information that confirms pre-existing beliefs while ignoring contradictory evidence.",
            "Impact on Decisions": "Causes decision-makers to build a one-sided case for their preferred option, systematically underweighting evidence against it.",
            "How to Detect": "Ask: Have we actively sought evidence AGAINST our preferred option? Are we explaining away contradictory data?",
            "Debiasing Strategy": "Assign a devil's advocate role. Explicitly seek disconfirming evidence for the leading option. Require equal analysis of all options.",
            "Example": "A team evaluating a new market entry only gathers data supporting the opportunity while dismissing negative market signals.",
            "Severity": "High",
        },
        {
            "Bias": "Anchoring Effect",
            "Category": "information-processing",
            "Keywords": "anchoring, first impression, initial value, reference point, starting point, adjustment insufficient",
            "Description": "Over-weighting the first piece of information encountered (the anchor) and insufficiently adjusting from it when making subsequent judgments.",
            "Impact on Decisions": "First option presented, first number mentioned, or first opinion shared disproportionately influences the final decision.",
            "How to Detect": "Ask: Would our evaluation change if we had seen the options in a different order? Is the first proposal dominating the discussion?",
            "Debiasing Strategy": "Generate evaluation criteria BEFORE seeing any options. Use structured scoring independently before group discussion. Randomize option presentation order.",
            "Example": "A vendor's initial price quote becomes the anchor, and all negotiation revolves around that number rather than true market value.",
            "Severity": "High",
        },
        {
            "Bias": "Sunk Cost Fallacy",
            "Category": "emotional",
            "Keywords": "sunk cost, past investment, throwing good money after bad, committed, already spent, waste aversion",
            "Description": "Continuing with a failing course of action because of past investment (time, money, effort) rather than evaluating future value.",
            "Impact on Decisions": "Prevents abandoning failing options because 'we've already invested too much.' Past costs are irrelevant to future decisions but feel otherwise.",
            "How to Detect": "Ask: If we were starting fresh today with no prior investment, would we still choose this option? Are we justifying continuation by pointing to past spend?",
            "Debiasing Strategy": "Evaluate each option as if starting fresh today (zero-based evaluation). Separate the past investment discussion from the forward-looking decision.",
            "Example": "Continuing to develop a product feature that shows poor user adoption because the team has already spent 6 months building it.",
            "Severity": "High",
        },
        {
            "Bias": "Status Quo Bias",
            "Category": "emotional",
            "Keywords": "status quo, default, inertia, change aversion, current state, comfort zone, do nothing",
            "Description": "Preferring the current state of affairs simply because it is the current state, even when change would produce better outcomes.",
            "Impact on Decisions": "The status quo gets an unfair advantage in evaluation. Change requires a higher burden of proof than maintaining the current approach.",
            "How to Detect": "Ask: Are we holding the status quo to the same standard as alternatives? Would we actively choose the current approach if starting from scratch?",
            "Debiasing Strategy": "Explicitly include status quo as one option evaluated with the same rigor as all alternatives. Calculate the cost of inaction.",
            "Example": "A company continues using an outdated CRM system because switching feels risky, even though the annual cost of inefficiency exceeds migration cost.",
            "Severity": "Medium",
        },
        {
            "Bias": "Overconfidence",
            "Category": "probability",
            "Keywords": "overconfidence, calibration, confidence interval, prediction accuracy, too certain, know-it-all, hubris",
            "Description": "Overestimating the accuracy of own predictions, knowledge, and judgment. Expressing certainty well beyond what evidence supports.",
            "Impact on Decisions": "Leads to too-narrow confidence intervals, insufficient contingency planning, and rejection of ambiguity that should inform the decision.",
            "How to Detect": "Ask: What is our confidence level, and what is it based on? Have we been right about similar predictions before? Are our confidence intervals wide enough?",
            "Debiasing Strategy": "Use pre-mortem to stress-test confidence. Assign explicit confidence levels and track calibration over time. Seek outside perspectives.",
            "Example": "A project manager estimates delivery in 3 months with 90% confidence, despite a track record of similar projects taking 5-7 months.",
            "Severity": "High",
        },
        {
            "Bias": "Framing Effect",
            "Category": "information-processing",
            "Keywords": "framing, gain frame, loss frame, presentation, wording, perspective, positive negative, context dependent",
            "Description": "Reaching different conclusions from the same information depending on how it is presented — as a gain vs. a loss, as a percentage vs. absolute number.",
            "Impact on Decisions": "The way options are framed (gain vs. loss, survival vs. mortality) systematically shifts preferences even when the underlying facts are identical.",
            "How to Detect": "Ask: Would our preference change if this were framed differently? Are we reacting to the framing or the substance?",
            "Debiasing Strategy": "Deliberately reframe the decision both as gains and as losses. Check if the conclusion changes. Present data in multiple formats.",
            "Example": "A treatment described as having a 90% survival rate is preferred over one described as having a 10% mortality rate, though they are identical.",
            "Severity": "Medium",
        },
        {
            "Bias": "Availability Heuristic",
            "Category": "memory",
            "Keywords": "availability, vivid, recent, memorable, anecdote, easily recalled, dramatic, salient event",
            "Description": "Overweighting information that is easily recalled (vivid, recent, emotionally charged) when estimating probabilities or making judgments.",
            "Impact on Decisions": "Recent dramatic events distort probability estimates. A vivid failure story outweighs statistical base rates in our judgment.",
            "How to Detect": "Ask: Are we basing this estimate on systematic data or on memorable anecdotes? Is a recent event disproportionately influencing our assessment?",
            "Debiasing Strategy": "Use base rates from systematic data rather than anecdotes. Seek statistical evidence. Ask: what does the aggregate data say, not just the vivid examples?",
            "Example": "After a highly publicized startup failure, investors become disproportionately risk-averse about an entire sector despite strong aggregate returns.",
            "Severity": "Medium",
        },
        {
            "Bias": "Groupthink",
            "Category": "social",
            "Keywords": "groupthink, conformity, consensus, dissent suppressed, harmony, team pressure, unanimity illusion",
            "Description": "A group converges on a preferred option without critical evaluation because members prioritize harmony and consensus over honest assessment.",
            "Impact on Decisions": "The group fails to surface dissenting views, alternative options, or risk information. Creates an illusion of unanimity that masks true disagreement.",
            "How to Detect": "Ask: Has anyone expressed strong disagreement? Are we reaching consensus suspiciously fast? Are quieter team members actually aligned or just silent?",
            "Debiasing Strategy": "Use structured dissent techniques: pre-mortem, red team, anonymous input. Assign a devil's advocate. Create psychological safety for disagreement.",
            "Example": "A leadership team unanimously approves an acquisition despite private doubts from several members who feel unable to challenge the CEO's enthusiasm.",
            "Severity": "High",
        },
        {
            "Bias": "Planning Fallacy",
            "Category": "probability",
            "Keywords": "planning fallacy, optimistic timeline, underestimate, cost overrun, schedule slip, best case thinking",
            "Description": "Systematically underestimating the time, cost, and risk of future actions while overestimating their benefits, even when aware of similar past overruns.",
            "Impact on Decisions": "The chosen option appears more attractive than it actually is because its costs and timelines are underestimated. Distorts option comparison.",
            "How to Detect": "Ask: Are our estimates based on best-case assumptions? Have similar projects in the past taken longer or cost more than planned?",
            "Debiasing Strategy": "Use reference class forecasting — compare to actual outcomes of similar past decisions rather than building bottom-up estimates from scratch.",
            "Example": "A team estimates a software migration will take 4 months and cost $200K. Similar past migrations averaged 9 months and $500K.",
            "Severity": "Medium",
        },
        {
            "Bias": "Loss Aversion",
            "Category": "emotional",
            "Keywords": "loss aversion, risk averse, fear of loss, prospect theory, downside, potential loss weighs more, regret",
            "Description": "Weighing potential losses approximately twice as heavily as equivalent gains, leading to excessive risk avoidance and status quo preference.",
            "Impact on Decisions": "Decision-makers reject options with positive expected value because the potential downside feels disproportionately painful compared to the upside.",
            "How to Detect": "Ask: Are we avoiding this option primarily because of what we might lose, rather than evaluating the full picture? Would we accept this bet if offered as a gain?",
            "Debiasing Strategy": "Reframe in terms of opportunity cost — what do we lose by NOT acting? Evaluate gains and losses on the same scale. Consider the cost of inaction.",
            "Example": "A company refuses to enter a promising new market because the potential $2M loss looms larger than the expected $5M gain.",
            "Severity": "Medium",
        },
        {
            "Bias": "Recency Bias",
            "Category": "memory",
            "Keywords": "recency, recent events, short-term memory, latest data, recent trend, extrapolation, last quarter",
            "Description": "Overweighting recent events and trends when evaluating options, while ignoring longer-term base rates and historical patterns.",
            "Impact on Decisions": "A recent success or failure with a similar approach disproportionately influences the current decision, regardless of long-term track record.",
            "How to Detect": "Ask: Are we extrapolating from the last few data points? Would our assessment change if we looked at 5-10 years of data instead of the last quarter?",
            "Debiasing Strategy": "Extend the time horizon of analysis. Look at 5-10 year data, not just the recent period. Explicitly seek base rates across full business cycles.",
            "Example": "After two strong quarters, a team extrapolates growth and approves aggressive expansion, ignoring the cyclical nature of their industry.",
            "Severity": "Medium",
        },
        {
            "Bias": "Survivorship Bias",
            "Category": "information-processing",
            "Keywords": "survivorship, success stories, invisible failures, selection bias, winners only, survivor, hidden data",
            "Description": "Drawing conclusions from successful examples while ignoring failures that followed the same approach but are no longer visible.",
            "Impact on Decisions": "Options appear more promising than they are because we only see the winners and not the many failures that used the same strategy.",
            "How to Detect": "Ask: Are we only looking at successful cases? Who tried this approach and failed? What happened to the alternatives we aren't seeing?",
            "Debiasing Strategy": "Actively seek failed examples of each option under consideration. Ask: who tried this and failed, and why? Analyze the full population, not just survivors.",
            "Example": "A team studies 5 successful companies that used a particular strategy, without examining the 50 companies that used the same strategy and went bankrupt.",
            "Severity": "Medium",
        },
    ]
    write_csv("cognitive-biases.csv", headers, rows)


def populate_analysis():
    headers = ["Technique", "Category", "Keywords", "Description", "When to Use", "Inputs Required", "How to Apply", "Output Format", "Strengths", "Limitations", "Complexity"]
    rows = [
        {
            "Technique": "Sensitivity Analysis",
            "Category": "quantitative",
            "Keywords": "sensitivity, tornado chart, assumption testing, variable impact, what-if, robustness, key drivers",
            "Description": "Systematically varies each input assumption to determine which ones most affect the decision outcome. Reveals decision drivers and noise.",
            "When to Use": "When the decision depends on uncertain assumptions and you need to know which ones actually matter",
            "Inputs Required": "Key variables, plausible range for each variable, a decision model or scoring framework",
            "How to Apply": "1. Identify key input variables. 2. Define plausible range (low-base-high) for each. 3. Vary one variable at a time while holding others at base. 4. Record impact on decision outcome. 5. Rank variables by impact magnitude. 6. Focus resources on high-impact uncertain variables.",
            "Output Format": "Tornado chart showing which variables have the most impact on the decision; sensitivity table with breakpoints",
            "Strengths": "Reveals what matters most; prevents over-analysis of non-sensitive inputs; builds decision confidence",
            "Limitations": "Assumes variables are independent; one-at-a-time variation misses interaction effects; requires quantifiable model",
            "Complexity": "Medium",
        },
        {
            "Technique": "Break-Even Analysis",
            "Category": "quantitative",
            "Keywords": "break-even, threshold, payback, minimum viable, go no-go, investment threshold, return",
            "Description": "Calculates the point at which an option becomes viable — the minimum performance needed to justify the investment.",
            "When to Use": "Evaluating go/no-go investment decisions or comparing options with different cost structures",
            "Inputs Required": "Fixed costs, variable costs per unit, revenue or value per unit, time horizon",
            "How to Apply": "1. Identify all fixed costs of the option. 2. Identify variable costs per unit of activity. 3. Identify value generated per unit. 4. Calculate: break-even = fixed costs / (value per unit - variable cost per unit). 5. Assess plausibility of reaching break-even. 6. Calculate margin of safety.",
            "Output Format": "Break-even point (units or time); margin of safety; payback period chart",
            "Strengths": "Simple and clear; communicates viability threshold; helps set minimum success criteria",
            "Limitations": "Assumes linear relationships; may oversimplify complex cost structures; ignores qualitative factors",
            "Complexity": "Low",
        },
        {
            "Technique": "Decision Tree Analysis",
            "Category": "quantitative",
            "Keywords": "decision tree, sequential choices, probability branches, expected value, optimal path, nodes, payoff",
            "Description": "Maps sequential decision points and chance events as a tree, assigns probabilities and payoffs to branches, calculates optimal path.",
            "When to Use": "When the decision involves sequential choices with probabilistic outcomes at each stage",
            "Inputs Required": "Decision points, possible outcomes at each point, probability estimates, payoff values for terminal nodes",
            "How to Apply": "1. Draw decision nodes (squares) and chance nodes (circles). 2. Add branches for each option/outcome. 3. Assign probabilities to chance branches (must sum to 1.0). 4. Assign payoff values to terminal nodes. 5. Calculate expected value by rolling back from terminal nodes. 6. Choose the path with highest expected value.",
            "Output Format": "Decision tree diagram; expected value for each path; recommended action at each node",
            "Strengths": "Handles sequential decisions; makes probabilities and payoffs explicit; visual and communicable; handles option value",
            "Limitations": "Quickly becomes complex with many branches; requires probability estimates; assumes rational decision-maker",
            "Complexity": "High",
        },
        {
            "Technique": "Scenario Analysis",
            "Category": "qualitative",
            "Keywords": "scenario, futures, external uncertainty, environment, robustness, what-if world, plausible futures",
            "Description": "Evaluates how each option performs under multiple plausible future scenarios, testing robustness rather than optimizing for one forecast.",
            "When to Use": "When multiple external uncertainties interact and the future environment is genuinely unknowable",
            "Inputs Required": "2-3 key external uncertainties, 2-3 plausible values for each, options to evaluate",
            "How to Apply": "1. Identify 2-3 key external uncertainties. 2. Build scenario matrix from combinations. 3. Name and describe each scenario. 4. Evaluate each option under each scenario. 5. Identify which options are robust (perform well across scenarios). 6. Develop contingency plans for adverse scenarios.",
            "Output Format": "Scenario matrix table; option performance across scenarios; robustness ranking",
            "Strengths": "Handles deep uncertainty; avoids overcommitment to single forecast; builds preparedness",
            "Limitations": "Subjective scenario selection; does not assign probabilities; can generate too many combinations",
            "Complexity": "Medium",
        },
        {
            "Technique": "Relative Value Scoring",
            "Category": "hybrid",
            "Keywords": "relative scoring, comparison, criteria-based, normalized, weighted, multi-criteria, ranking",
            "Description": "Scores options against criteria on a standardized scale, applies weights, and produces a transparent ranking.",
            "When to Use": "Comparing 3+ options across incommensurable criteria where a transparent ranking is needed",
            "Inputs Required": "Options list, evaluation criteria, weight per criterion, scoring rubric (1-5 scale)",
            "How to Apply": "1. Define criteria and weights (sum to 100). 2. Create scoring rubric (what does 1-5 mean for each criterion). 3. Score each option independently on each criterion. 4. Calculate weighted score per option. 5. Rank by total weighted score. 6. Perform sensitivity check on weights.",
            "Output Format": "Scoring matrix with weighted totals; ranked option list; sensitivity notes",
            "Strengths": "Transparent and repeatable; handles diverse criteria; facilitates group alignment; auditable",
            "Limitations": "Precision can be illusory; weight selection is subjective; scores depend on rubric quality",
            "Complexity": "Medium",
        },
        {
            "Technique": "Opportunity Cost Assessment",
            "Category": "qualitative",
            "Keywords": "opportunity cost, forgone alternatives, true cost, what else, trade-off, next best alternative, sacrifice",
            "Description": "Evaluates the true cost of choosing an option by explicitly measuring what is sacrificed — the value of the next-best alternative.",
            "When to Use": "When choosing one option means forgoing others that have significant value",
            "Inputs Required": "All viable options, value estimates for each, constraints that force trade-offs",
            "How to Apply": "1. List all viable options. 2. Estimate the value/benefit of each. 3. Identify which options become unavailable if you choose each one. 4. Calculate opportunity cost = value of best forgone alternative. 5. True cost = direct cost + opportunity cost. 6. Compare options on total cost basis.",
            "Output Format": "Opportunity cost table showing direct cost, forgone value, and total cost for each option",
            "Strengths": "Reveals hidden costs; prevents narrow framing; forces consideration of alternatives; improves resource allocation",
            "Limitations": "Value of alternatives may be hard to estimate; can create decision fatigue; not all forgone options are clear",
            "Complexity": "Low",
        },
        {
            "Technique": "Risk-Reward Matrix",
            "Category": "hybrid",
            "Keywords": "risk-reward, probability of success, impact, 2x2 matrix, risk profile, upside downside, positioning",
            "Description": "Positions each option on a 2x2 matrix of probability of success (x-axis) vs. magnitude of reward (y-axis). Reveals risk-adjusted option positioning.",
            "When to Use": "When options have distinctly different risk profiles and you need a visual comparison",
            "Inputs Required": "Each option's estimated probability of success and magnitude of reward/impact, plus downside risk",
            "How to Apply": "1. List all options. 2. Estimate probability of success for each (0-100%). 3. Estimate magnitude of reward if successful. 4. Plot on 2x2 matrix. 5. Categorize: high-prob/high-reward (do first), high-prob/low-reward (easy wins), low-prob/high-reward (strategic bets), low-prob/low-reward (avoid). 6. Select based on risk appetite.",
            "Output Format": "2x2 matrix with options positioned; quadrant labels; recommended priority order",
            "Strengths": "Visual and intuitive; enables portfolio thinking; quick to create; good for communication",
            "Limitations": "Two-dimensional simplification; probability estimates may be unreliable; ignores correlation between options",
            "Complexity": "Low",
        },
        {
            "Technique": "Bayesian Update Protocol",
            "Category": "quantitative",
            "Keywords": "bayesian, prior probability, posterior, evidence update, likelihood, new information, belief revision",
            "Description": "Formally updates probability estimates when new evidence arrives during the decision process, preventing both over-reaction and under-reaction.",
            "When to Use": "When new evidence arrives during the decision process and you need to update beliefs rationally",
            "Inputs Required": "Prior probability estimate for each option, new evidence, likelihood of evidence under each hypothesis",
            "How to Apply": "1. State prior probabilities for each option being correct. 2. New evidence arrives. 3. Ask: How likely is this evidence if Option A is correct? If Option B? 4. Apply Bayes rule: Posterior = (Likelihood x Prior) / Evidence. 5. Update probabilities. 6. Check if new probabilities change the decision.",
            "Output Format": "Updated probability table; decision shift analysis; confidence change log",
            "Strengths": "Rational evidence integration; prevents overreaction to single data points; cumulative learning; tracks belief evolution",
            "Limitations": "Requires probability estimates; computationally involved for many options; prior selection is subjective",
            "Complexity": "High",
        },
        {
            "Technique": "Pre-Mortem Analysis",
            "Category": "qualitative",
            "Keywords": "pre-mortem, prospective hindsight, failure analysis, risk identification, blind spots, assume failure, what could go wrong",
            "Description": "Assumes the decision has already been made and failed. Participants work backward to identify what went wrong, surfacing risks invisible in forward-looking analysis.",
            "When to Use": "Before committing to a high-stakes or irreversible decision where hidden risks could be catastrophic",
            "Inputs Required": "Proposed decision, team of 3-12 people, 30-60 minutes",
            "How to Apply": "1. State the proposed decision. 2. Fast-forward: imagine it is 12 months later and the decision failed spectacularly. 3. Each person independently writes what went wrong. 4. Share all failure modes. 5. Categorize by likelihood and severity. 6. Develop mitigation plans for high-risk items.",
            "Output Format": "Ranked list of failure modes with likelihood, severity, and mitigation plans",
            "Strengths": "Surfaces hidden risks; overcomes optimism bias; psychologically safe; works well in groups; simple to facilitate",
            "Limitations": "Can be demoralizing if overused; may generate unlikely risks; depends on honest participation",
            "Complexity": "Low",
        },
        {
            "Technique": "Reference Class Forecasting",
            "Category": "meta-analysis",
            "Keywords": "reference class, base rate, outside view, historical comparison, similar decisions, prediction accuracy, anchoring to data",
            "Description": "Predicts outcomes by comparing the current decision to a reference class of similar past decisions, using actual outcomes rather than inside-view estimates.",
            "When to Use": "When estimating costs, timelines, or outcomes of a chosen option where similar past decisions exist",
            "Inputs Required": "Identification of similar past decisions, their actual outcomes, adjustments for material differences",
            "How to Apply": "1. Identify reference class (similar past decisions). 2. Gather actual outcome data (cost, time, success rate). 3. Calculate distribution (mean, range). 4. Identify where current decision sits relative to class. 5. Adjust for material differences. 6. Use reference class prediction as baseline, not inside-view estimate.",
            "Output Format": "Base rate prediction; confidence interval from reference class; comparison to inside-view estimate; adjustment rationale",
            "Strengths": "Counters planning fallacy; grounded in real data; simple to explain; highly accurate in aggregate",
            "Limitations": "Requires finding truly comparable decisions; reference class selection is subjective; unique situations may lack reference class",
            "Complexity": "Medium",
        },
    ]
    write_csv("analysis-techniques.csv", headers, rows)


def populate_criteria():
    headers = ["Domain", "Keywords", "Description", "Criteria", "Default Weights", "Measurement Guidance", "Common Mistakes"]
    rows = [
        {
            "Domain": "Technology Selection",
            "Keywords": "technology, software, platform, tool, system, tech stack, SaaS, infrastructure, migration",
            "Description": "Evaluating technology platforms, software tools, or technical infrastructure where functionality, integration, and long-term viability matter.",
            "Criteria": "Functionality fit,Integration ease,Total cost of ownership,Vendor stability,Scalability,Security,Team capability",
            "Default Weights": "20,15,15,10,15,10,15",
            "Measurement Guidance": "Functionality: 5=covers 95%+ requirements. Integration: 5=plug-and-play with current stack. Cost: 5=lowest TCO over 3 years. Vendor: 5=established leader with strong roadmap. Scalability: 5=handles 10x current load. Security: 5=exceeds compliance requirements. Team: 5=team has deep expertise.",
            "Common Mistakes": "Overweighting features while ignoring integration costs. Not including migration effort in TCO. Evaluating current needs without growth projection.",
        },
        {
            "Domain": "Hiring Decision",
            "Keywords": "hiring, candidate, recruitment, talent, people, team member, employee, role, interview, skills",
            "Description": "Evaluating candidates for a position where skills, cultural fit, and growth potential must be balanced against availability and compensation.",
            "Criteria": "Skills match,Culture fit,Growth potential,Compensation alignment,Availability,References,Team complement",
            "Default Weights": "20,15,15,10,10,10,20",
            "Measurement Guidance": "Skills: 5=exceeds all technical requirements. Culture: 5=strong alignment with team values and work style. Growth: 5=clear trajectory to next-level role. Compensation: 5=within budget with room for growth. Availability: 5=can start immediately. References: 5=exceptional references from credible sources. Complement: 5=fills a clear gap in team capabilities.",
            "Common Mistakes": "Hiring for current skills only without considering adaptability. Culture fit becoming sameness rather than values alignment. Anchoring on impressive resume over actual capability.",
        },
        {
            "Domain": "Vendor / Partner Selection",
            "Keywords": "vendor, partner, supplier, outsource, contract, service provider, procurement, third-party",
            "Description": "Evaluating vendors, suppliers, or partners where reliability, alignment, and long-term relationship quality are critical.",
            "Criteria": "Quality of deliverables,Price competitiveness,Reliability track record,Strategic alignment,Flexibility,Reputation,Integration effort",
            "Default Weights": "20,15,15,15,10,10,15",
            "Measurement Guidance": "Quality: 5=consistently exceeds standards. Price: 5=best value (not necessarily cheapest). Reliability: 5=100% on-time delivery track record. Alignment: 5=shared vision and complementary goals. Flexibility: 5=highly adaptable to changing requirements. Reputation: 5=industry leader with excellent references. Integration: 5=seamless integration with existing processes.",
            "Common Mistakes": "Choosing the lowest bidder without considering quality and reliability. Not checking references from similar-sized clients. Ignoring cultural compatibility in long-term partnerships.",
        },
        {
            "Domain": "Investment / Resource Allocation",
            "Keywords": "investment, resource allocation, funding, budget, capital, ROI, return, portfolio, financial decision",
            "Description": "Deciding where to invest limited resources (capital, time, people) for maximum return adjusted for risk and strategic value.",
            "Criteria": "Expected return,Risk level,Strategic alignment,Time to value,Resource requirement,Opportunity cost",
            "Default Weights": "20,15,20,15,15,15",
            "Measurement Guidance": "Return: 5=highest projected ROI with strong evidence. Risk: 5=lowest risk with clear mitigation. Strategic: 5=directly advances top strategic priority. Time: 5=delivers value within 3 months. Resource: 5=minimal resource requirement relative to return. Opportunity: 5=lowest cost of forgone alternatives.",
            "Common Mistakes": "Spreading resources equally instead of prioritizing (peanut butter fallacy). Ignoring opportunity cost of capital. Underweighting time-to-value in fast-moving markets.",
        },
        {
            "Domain": "Market Entry / Expansion",
            "Keywords": "market entry, expansion, new market, geographic, international, growth, launch, go-to-market",
            "Description": "Evaluating whether and how to enter or expand into new markets where external factors and competitive dynamics dominate.",
            "Criteria": "Market size and growth,Competition intensity,Barrier to entry,Capability fit,Regulatory risk,Timing,Profitability potential",
            "Default Weights": "20,15,10,15,10,15,15",
            "Measurement Guidance": "Market: 5=large and growing rapidly. Competition: 5=fragmented market with clear differentiation opportunity. Barrier: 5=low barriers matching our strengths. Capability: 5=strong existing capability requiring minimal investment. Regulatory: 5=favorable, stable regulatory environment. Timing: 5=clear first-mover or fast-follower advantage. Profitability: 5=strong unit economics proven by comparable players.",
            "Common Mistakes": "Overweighting market size without analyzing competitive dynamics. Ignoring regulatory complexity until too late. Assuming domestic success translates directly to new markets.",
        },
        {
            "Domain": "Product Feature Prioritization",
            "Keywords": "feature prioritization, product, roadmap, backlog, user stories, sprint, requirements, product management",
            "Description": "Prioritizing which product features to build when development capacity is limited and user needs compete with business goals.",
            "Criteria": "User impact,Revenue impact,Implementation effort,Strategic alignment,Urgency,Dependency",
            "Default Weights": "25,20,15,15,15,10",
            "Measurement Guidance": "User: 5=addresses top pain point for majority of users. Revenue: 5=directly drives measurable revenue growth. Effort: 5=small effort, ship within one sprint. Strategic: 5=enables key strategic initiative. Urgency: 5=time-sensitive competitive or contractual requirement. Dependency: 5=unblocks multiple other features.",
            "Common Mistakes": "Building what the loudest customer asks for instead of highest-impact features. Not distinguishing urgency from importance. Ignoring technical debt as a feature choice.",
        },
        {
            "Domain": "Organizational Change",
            "Keywords": "organizational change, restructuring, transformation, culture, process change, reorganization, change management",
            "Description": "Evaluating organizational changes (restructuring, process changes, cultural shifts) where people impact and change readiness are critical.",
            "Criteria": "Impact on people,Implementation complexity,Reversibility,Cost,Timeline,Stakeholder support",
            "Default Weights": "20,15,15,15,15,20",
            "Measurement Guidance": "People: 5=positive impact on engagement and capability. Complexity: 5=straightforward implementation with clear steps. Reversibility: 5=easily reversed if not working. Cost: 5=minimal direct and indirect costs. Timeline: 5=achievable within one quarter. Stakeholder: 5=strong support from all key stakeholders.",
            "Common Mistakes": "Underestimating people impact and change resistance. Not securing stakeholder buy-in before announcing. Ignoring the time and resources needed for change management.",
        },
        {
            "Domain": "Location / Facility",
            "Keywords": "location, facility, office, headquarters, warehouse, site selection, real estate, geographic, relocation",
            "Description": "Selecting physical locations for offices, facilities, or operations where cost, access to talent, and strategic positioning are balanced.",
            "Criteria": "Cost,Talent access,Infrastructure quality,Quality of life,Regulatory environment,Strategic proximity",
            "Default Weights": "20,15,15,15,15,20",
            "Measurement Guidance": "Cost: 5=lowest total occupancy cost meeting requirements. Talent: 5=deep talent pool in required specialties. Infrastructure: 5=excellent connectivity, power, and facilities. Quality: 5=highly desirable location for employee recruitment and retention. Regulatory: 5=business-friendly environment with clear regulations. Proximity: 5=optimal location relative to customers, partners, and supply chain.",
            "Common Mistakes": "Choosing based on tax incentives alone without considering talent availability. Ignoring quality of life impact on recruitment. Not factoring in long-term cost trends.",
        },
    ]
    write_csv("criteria-templates.csv", headers, rows)


def populate_facilitation():
    headers = ["Technique", "Category", "Keywords", "Description", "When to Use", "Group Size", "Time Required", "Steps", "Counters Bias", "Output"]
    rows = [
        {
            "Technique": "Pre-Mortem",
            "Category": "stress-test",
            "Keywords": "pre-mortem, failure analysis, risk identification, hidden risks, prospective hindsight, blind spots",
            "Description": "The group assumes the decision has already been made and failed catastrophically. Participants work backward to identify what went wrong.",
            "When to Use": "Before committing to a high-stakes decision; surfaces hidden risks and breaks optimism bias in groups",
            "Group Size": "3-12",
            "Time Required": "30-60 min",
            "Steps": "1. Facilitator states the proposed decision clearly. 2. Ask the group to imagine it is 12 months later and the decision failed spectacularly. 3. Each person independently writes 3-5 reasons it failed (5 min silent). 4. Go around the room, each person shares one reason per round. 5. Compile all failure modes on a shared board. 6. Vote on most likely and most severe. 7. For top risks, develop mitigation plans or reconsider decision.",
            "Counters Bias": "Overconfidence, Groupthink, Planning Fallacy",
            "Output": "Prioritized list of failure modes with mitigation plans; revised risk assessment",
        },
        {
            "Technique": "Red Team Challenge",
            "Category": "stress-test",
            "Keywords": "red team, adversarial, challenge, attack, critique, stress test, opposing view, counter-argument",
            "Description": "A dedicated sub-group is tasked with building the strongest possible case AGAINST the proposed decision, using all available evidence.",
            "When to Use": "When the group seems too aligned too quickly; provides adversarial testing of the preferred option",
            "Group Size": "4-8",
            "Time Required": "60-120 min",
            "Steps": "1. Assign 2-3 people as the Red Team. 2. Red Team prepares the strongest case against the proposed decision (30-45 min). 3. Main group presents the case for the decision (15 min). 4. Red Team presents their counter-case (15 min). 5. Open discussion focusing on the strongest counter-arguments. 6. Decision-maker summarizes: which Red Team points change the decision or require mitigation?",
            "Counters Bias": "Confirmation Bias, Groupthink, Overconfidence",
            "Output": "Counter-arguments ranked by strength; decision modifications; risk mitigations from adversarial analysis",
        },
        {
            "Technique": "Nominal Group Technique",
            "Category": "divergent",
            "Keywords": "nominal group, silent generation, equal voice, democratic, structured brainstorm, round-robin, balanced input",
            "Description": "Structured process ensuring every participant contributes ideas independently before group discussion, preventing dominant voices from suppressing input.",
            "When to Use": "When dominant voices or hierarchy suppress diverse input; ensuring every person's perspective is captured",
            "Group Size": "5-15",
            "Time Required": "45-90 min",
            "Steps": "1. State the decision question clearly. 2. Silent idea generation: each person writes their thoughts independently (10 min). 3. Round-robin sharing: each person shares one idea per round (no discussion yet). 4. Group discussion: clarify and explore each idea. 5. Independent ranking: each person privately ranks their top options. 6. Tally votes and discuss the results.",
            "Counters Bias": "Groupthink, Anchoring Effect",
            "Output": "Ranked list of options with vote counts; diverse perspectives captured; transparent prioritization",
        },
        {
            "Technique": "Structured Debate (Steel Man)",
            "Category": "convergent",
            "Keywords": "structured debate, steel man, strongest argument, fair comparison, two options, rigorous, adversarial collaboration",
            "Description": "Two teams present the strongest possible case (steel man, not straw man) for opposing options, enabling rigorous comparison of the best version of each.",
            "When to Use": "When two strong options exist and the group needs rigorous comparison rather than superficial pros-cons",
            "Group Size": "4-10",
            "Time Required": "60-90 min",
            "Steps": "1. Identify the two leading options. 2. Divide into two teams (ideally mixing genuine preferences). 3. Each team prepares the strongest case for their assigned option (20 min). 4. Team A presents (10 min), Team B asks clarifying questions (5 min). 5. Team B presents (10 min), Team A asks clarifying questions (5 min). 6. Open discussion. 7. Individual vote or decision-maker decides.",
            "Counters Bias": "Confirmation Bias, Framing Effect",
            "Output": "Side-by-side comparison of strongest cases; balanced evaluation; decision with documented rationale",
        },
        {
            "Technique": "Dot Voting Prioritization",
            "Category": "convergent",
            "Keywords": "dot voting, democratic prioritization, quick ranking, simple voting, group priority, rapid alignment",
            "Description": "Each participant allocates a fixed number of votes (dots) across options, producing a quick democratic ranking of preferences.",
            "When to Use": "Quick democratic ranking of criteria, options, or priorities when time is limited and approximate consensus is sufficient",
            "Group Size": "3-20",
            "Time Required": "15-30 min",
            "Steps": "1. List all options/criteria on a visible board. 2. Give each participant N dots (typically 3-5, roughly 1/3 of total options). 3. Each person places dots on their priority items (can stack or spread). 4. Count dots per item. 5. Rank by total dots. 6. Discuss top-ranked items and any surprising results.",
            "Counters Bias": "Groupthink, Anchoring Effect",
            "Output": "Ranked list of priorities by group vote; visual heat map of preferences; quick consensus check",
        },
        {
            "Technique": "Anonymous Input Round",
            "Category": "divergent",
            "Keywords": "anonymous, secret ballot, hidden input, honest opinion, hierarchy-free, safe, written input, candid",
            "Description": "Participants submit their real opinions or concerns anonymously before any group discussion, neutralizing hierarchy and political pressure.",
            "When to Use": "When hierarchy, politics, or social pressure bias open discussion; getting honest input from all levels",
            "Group Size": "3-30",
            "Time Required": "20-40 min",
            "Steps": "1. Frame the decision question clearly. 2. Distribute anonymous submission method (digital form or paper). 3. Each person submits their honest assessment: preferred option and top concerns (10 min). 4. Collect and display all submissions without attribution. 5. Facilitator groups themes and highlights surprising inputs. 6. Discuss the anonymous themes openly. 7. Move to named discussion now that all perspectives are surfaced.",
            "Counters Bias": "Groupthink, Status Quo Bias",
            "Output": "Unfiltered perspectives from all participants; honest assessment of concerns; foundation for transparent discussion",
        },
        {
            "Technique": "Devil's Advocate Assignment",
            "Category": "stress-test",
            "Keywords": "devil's advocate, critical challenge, appointed critic, question assumptions, constructive opposition, designated dissenter",
            "Description": "One person is formally assigned to challenge the preferred option, ensuring critical thinking even when the group converges on a choice.",
            "When to Use": "When the group has a preferred option that needs critical challenge before commitment; prevents premature consensus",
            "Group Size": "3-8",
            "Time Required": "30-60 min",
            "Steps": "1. Identify the favored option. 2. Assign one person as devil's advocate (rotate this role across decisions). 3. Devil's advocate prepares the strongest counter-case (15 min). 4. Group presents the case for the favored option. 5. Devil's advocate challenges with counter-arguments, questions, and alternative interpretations. 6. Group addresses each challenge. 7. Document which challenges were resolved and which remain as risks.",
            "Counters Bias": "Confirmation Bias, Groupthink, Overconfidence",
            "Output": "List of challenges to preferred option; unresolved risks documented; decision strengthened by stress testing",
        },
        {
            "Technique": "Workplan Alignment Session",
            "Category": "alignment",
            "Keywords": "workplan, alignment, execution, implementation, after decision, action items, owners, timeline, accountability",
            "Description": "After the decision is made, the group aligns on who does what by when — translating the decision into an executable workplan with clear accountability.",
            "When to Use": "After a major decision is made; aligning the team on execution plan to prevent decision-execution gap",
            "Group Size": "3-10",
            "Time Required": "60-120 min",
            "Steps": "1. Restate the decision clearly. 2. Break implementation into work streams. 3. For each work stream: define deliverables, owner, timeline, resources needed. 4. Identify dependencies between streams. 5. Set check-in milestones. 6. Each owner confirms understanding and commitment. 7. Document and distribute the workplan.",
            "Counters Bias": "Planning Fallacy",
            "Output": "Detailed workplan with owners, timelines, milestones, and dependencies; shared commitment to execution",
        },
    ]
    write_csv("facilitation.csv", headers, rows)


if __name__ == "__main__":
    print("Populating decision-making CSVs...")
    populate_frameworks()
    populate_types()
    populate_biases()
    populate_analysis()
    populate_criteria()
    populate_facilitation()
    print("\nDone! All 6 CSV files populated.")
